### PR TITLE
Apply Glia patches to Phoenix 1.6.2

### PR DESCRIPTION
**Pull request by bautrey37**
DO NOT DELETE THIS BRANCH.

This PR are to show the changes between the v1.6.2 phoenix release and the Glia patches. This PR is not meant to be merged, we will link our code to the `v1.6.2-glia` branch. 

Phoenix versions are upgraded in:
- https://github.com/salemove/transporter/pull/474
- https://github.com/salemove/visitor-js-api/pull/710 - REVERTED
- https://github.com/salemove/backend-web/pull/6876 - REVERTED

The reason for upgrading is to get the changes in https://github.com/phoenixframework/phoenix/pull/3708 which may help resolve `unmatched topic` errors like https://sentry.io/organizations/glia/issues/2733180193/?project=1859731. Upgrading to the latest Phoenix also has other useful changes as well.

The patches are taken from https://github.com/salemove/phoenix/commits/ca74888-glia. The patches could not be cleaned applied or were no longer applicable. 

- The `assets/js/phoenix.js` file from v1.5 was split up into multiple smaller files in v1.6. Therefore the JS patch changes had to be manually applied.

- https://github.com/phoenixframework/phoenix/pull/3821 PR implemented custom error responses, which conflicts with our solution of https://github.com/salemove/phoenix/commit/4876cff11d55d0fbb36a3ebce548f37987243836. Phoenix's version did not support custom error status codes, so to maintain original functionality I overwrote our changes from Phoenix changes to ensure the same behavior, to not risk breaking anything. These custom error codes are used in https://github.com/salemove/transporter/pull/320, https://github.com/salemove/visitor-js-api/pull/291, https://github.com/salemove/visitor-js-api/pull/280/commits/c89a015480ef4fd8b91780d7300bf25696ee71ed, and https://github.com/salemove/backend-web/pull/5950

- Webpack was removed in phoenix in replace of esbuild. https://github.com/phoenixframework/phoenix/pull/4377 / https://github.com/phoenixframework/phoenix/pull/4372. Therefore this commit is not needed: https://github.com/salemove/phoenix/commit/40869e35c5c96c0ac8addfde0658c8a8ea23ee9e

- `installer/templates/phx_static/phoenix.js` file no longer exists, therefore this does not need updating: https://github.com/salemove/phoenix/commit/3395c2dd4bd1f2061db09e10c377072c9df86b40#diff-d4085b6b2e82eef03cfec7474ad9a135ab9a86c02914984b5ad91bfd3bd2c9e3

### CODE REVIEW

**Comment by bautrey37** [comment]
Testing Phoenix changes with 
https://github.com/salemove/visitor-js-api/pull/710
https://github.com/salemove/transporter/pull/474

**Comment by urmastalimaa** [comment]
> Because of this custom error code solution, this commit 8c2fb43 is not needed.

I am unconvinced this is true as 8c2fb43 changes the JS, while https://github.com/phoenixframework/phoenix/pull/3821/files only changes the back end. It may be that 4876cff11d55d0fbb36a3ebce548f37987243836 is no longer necessary, but that also needs to be verified end-to-end.

> Webpack was removed in phoenix in replace of esbuild. Replace node+npm+webpack by esbuild phoenixframework/phoenix#4377 / Switch to esbuild, package js as ESM phoenixframework/phoenix#4372. Therefore this commit is not needed: 40869e3

Please double-check that `Phoenix` is not present on `window` in the visitor page.

**Comment by bautrey37** [comment]
> Please double-check that Phoenix is not present on window in the visitor page.


There is no `Phoenix` on the `window` on the visitor page. 

image

**Comment by bautrey37** [comment]
@urmastalimaa 

> I am unconvinced this is true as 8c2fb43 changes the JS, while https://github.com/phoenixframework/phoenix/pull/3821/files only changes the back end. It may be that 4876cff is no longer necessary, but that also needs to be verified end-to-end.

I was also not convinced. I updated the custom error code to use our solution instead of the Phoenix solution to maintain the same functionality. The unit tests pass for this and the services that use this new Phoenix version. I do not know how would I test the custom error code responses manually, maybe you would know how? 

Once this PR is approved, I'll open the other PR's that use this new phoenix version. 

The description has been updated to reflect the current state.

**Comment by urmastalimaa** [comment]
You should be able to test locally by making VisitorLimiter limit your visitors (can set to 0%) https://github.com/salemove/transporter/blob/16d5364591ff4440d92d2eb012977ce5f6002b3d/config/config.exs#L640-L642 This should result in a 503 to the client.

**Comment by bautrey37** [comment]
To test that the custom error status code is returned to the visitor app appropriately, I had to:

1. Change the Transporter config VisitorLimiter to:
```
config :transporter, Transporter.VisitorLimiter,
  enabled: true,
  percentage: 0
```
2. Use an incognito visitor because previously engaged visitors have a high priority and will not be limited. 
3. Check that this error occurs in visitor app console: `Pubsub unavailable, postponing reconnecting for at least 30000 ms`
4. The error log should have:
```
error:
   status: 503
````

image

**Comment by bautrey37** [comment]
Closing PR because of approvals on other PR's. Branch must stay open.

DO NOT DELETE BRANCH

**Pull request closed without merging**
