### PR TITLE
Fix reconnecting websockets on heartbeat timeout

### PR DESCRIPTION
**Pull request by laurglia**
In Google Chrome, when network connection is interrupted, the websocket
connections break but they do not properly close. The following happens:
- The `error` and `close` events are not triggered
- Sending data with `WebSocket#send` works without errors even though
the data is not actually sent
- When calling `WebSocket#close`, the websocket is not closed.
That is expected, as closing a websocket includes sending a closing
handshake which cannot be done when the underlying connection is broken.
The closing handshake is documented in the [WebSockets
Standard][websockets-standard].

Because of the behavior described above, Phoenix failed to reconnect
sockets with WebSocket transport. When heartbeat timed out, `WebSocket#close`
was used to close the connection but since the connection was broken,
sending the closing handshake failed, and the close event was not
triggered.

It seems like that after some time, after around 2--3 minutes, the
WebSocket finally closes (the `close` event triggers) but that is too
long period for our case. For example business rule requests via
websocket proxy requests can fail if the Phoenix socket is disconnected,
leading to critical failures if business rules are used for things like
setting visitor queues and showing the bubble.

This commit fixes the issue by "tearing down" the WebSocket connection
after heartbeat timeout instead of just attempting to close it. The
teardown functionality does not necessarily close the connection but it
will remove all references to it, allowing a new one to be created in
place of the current one.

I also needed to make some changes to the teardown functionality.
Previously, it was not necessary to remove listeners from the
connections because once a connection was closed, it was not able for it
to emit any events. However, now since the connection may actually stay
open for some time and emit a close event after a few minutes, then that
could cause problems if the connection was replaced with a new
connection. That is why we now we set `this.conn.onopen`,
`this.conn.onerror` and other listeners to no-ops when tearing down the
connection.

[websockets-standard]: https://websockets.spec.whatwg.org/#dom-websocket-close

AUTO-539

### CODE REVIEW

**Comment by indrekj** [comment]
Is this solving the same issue? https://github.com/salemove/channel/pull/37 cc @riiwo 

Will you also create a PR for the upstream?

**Comment by laurglia** [comment]
> Is this solving the same issue? [salemove/channel#37](https://github.com/salemove/channel/pull/37) cc @riiwo
> 
> Will you also create a PR for the upstream?

Yes to both. We discussed this briefly with Riivo already last week but we only talked about the problem itself and not about fix specifically.

**Review by indrekj — APPROVED** [review]
I hope we can get this into phoenix itself as well to keep the code divergence smaller

**Comment by riiwo** [comment]
> Is this solving the same issue? [salemove/channel#37](https://github.com/salemove/channel/pull/37) cc @riiwo
> 
> Will you also create a PR for the upstream?

Kind of - sort of. This is more general and would be a bit slow still for my use case. I have issues with unstable internet connection and message preview not updating when socket gets broken. So I still would like to have the monitoring I added in the channel repo. But maybe my change is not needed for transporter as this should solve the issue for that.

**Review by riiwo — CHANGES_REQUESTED** [review]
There is 1.6.11 glia tag already. Better to add to the latest one

**Review by riiwo — APPROVED** [review]

**Pull request merged**
